version: "3"
services:
  employee-jdbc:
    image: employee-jdbc
    ports:
      - "8080:8080"
    networks:
      - employee-mysql
    depends_on:
      - synergy_container

  mysqldb:
    image: mysql:latest
    networks:
      - employee-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=synergy

networks:
  employee-mysql: